#!/bin/bash

# title case conversion for the title
title=$(echo "$1" | sed 's/-/ /g' | gsed -e 's/.*/\L&/' -e 's/[a-z]*/\u&/g')

function postmetadata() {
echo "--- "
echo "title: \"$title\""
echo "author: \"$(echo $USER)\""
echo "tags: []"
echo "summary: \"\""
echo "created: \"$(date -j +"%Y-%m-%d %T")\""
echo "--- "
echo ""
echo "## $title {.post-title}"
}

if [ $# -ge 2 ]
then 
  # we want to put the metadata into a file
  postmetadata $1 > $2/posts/$1.md
  subl $2/posts/$1.md
else
  # otherwise just output to stdout
  postmetadata $1
fi

