#!/bin/bash

# title case conversion for the title
title=$(echo "$1" | sed -e 's/-\([a-z]\)/\u\1/g' -e 's/^[a-z]/\u&/')

echo "--- "
echo "title: \"$title\""
echo "author: \"$(echo $USER)\""
echo "tags: []"
echo "summary: \"\""
echo "created: \"$(date -j +"%Y-%m-%d %T")\""
echo "--- "
echo ""
echo "## $title {.post-title}"
