["OU", :Gliscor, "SubToxic", ["Toxic Orb", :Poison-Heal, :Impish, [244, 0, 28, 0, 0, 236]], [:Substitute, :Toxic, :Protect, :Earthquake]]
["OU", :Gliscor, "Specially Defensive", ["Toxic Orb", :Poison-Heal, :Careful, [244, 0, 0, 0, 192, 72]], [:Taunt, :Roost, :Toxic, :Earthquake]]
["OU", :Gliscor, "Physically Defensive", ["Toxic Orb", :Poison-Heal, :Impish, [252, 0, 56, 0, 0, 200]], [:Roost, :Taunt, :Acrobatics, :Earthquake]]
["OU", :Wobbuffet, "Oh no, it's Wobbuffet!", ["Leftovers", :Shadow-Tag, :Bold, [52, 0, 232, 0, 224, 0]], [:Encore, :Counter, :Mirror-Coat, :Safeguard]]
["OU", :Cresselia, "Dual Screens", ["Light Clay", "", :Bold, [248, 0, 112, 0, 12, 136]], [:Lunar-Dance, :Reflect, :Light-Screen, :Thunder-Wave]]
["OU", :Cresselia, "Defensive", ["Leftovers", "", :Bold, [252, 0, 252, 0, 4, 0]], [:Moonlight, :Psychic, :Ice-Beam, :Toxic]]
["OU", :Mega-Absol, "All-Out Attacker", ["Absolite", :Justified, :Jolly, [0, 252, 0, 32, 0, 224]], [:Sucker-Punch, :Knock-Off, :Fire-Blast, :Superpower]]
["OU", :Krookodile, "Offensive", ["Life Orb", :Moxie, :Jolly, [0, 252, 4, 0, 0, 252]], [:Earthquake, :Knock-Off, :Pursuit, :Stone-Edge]]
["OU", :Krookodile, "Support", ["Leftovers", :Intimidate, :Impish, [248, 8, 252, 0, 0, 0]], [:Earthquake, :Knock-Off, :Taunt, :Toxic]]
["OU", :Mega-Ampharos, "Agility", ["", "", :Modest, [4, 0, 0, 252, 0, 252]], [:Agility, :Thunderbolt, :Dragon-Pulse, :Focus-Blast]]
["OU", :Mega-Ampharos, "Specially Defensive", ["", "", :Calm, [248, 0, 0, 28, 232, 0]], [:Volt-Switch, :Dragon-Pulse, :Rest, :Sleep-Talk]]
["OU", :Mega-Aggron, "RestTalk", ["Aggronite", :Sturdy, :Impish, [252, 0, 16, 0, 240, 0]], [:Rest, :Sleep-Talk, :Iron-Head, :Earthquake]]
["OU", :Mega-Aggron, "Tank", ["Aggronite", :Sturdy, :Impish, [252, 0, 16, 0, 240, 0]], [:Stealth-Rock, :Iron-Head, :Ice-Punch, :Earthquake]]
["OU", :Slowbro, "Physical Wall", ["Leftovers", :Regenerator, :Bold, [252, 0, 232, 0, 24, 0]], [:Scald, :Fire-Blast, :Toxic, :Slack-Off]]
["OU", :Mega-Ampharos, "Agility", ["Ampharosite", :Static, :Modest, [4, 0, 0, 252, 0, 252]], [:Agility, :Thunderbolt, :Dragon-Pulse, :Focus-Blast]]
["OU", :Mega-Ampharos, "Specially Defensive", ["Ampharosite", :Static, :Calm, [248, 0, 0, 28, 232, 0]], [:Volt-Switch, :Dragon-Pulse, :Rest, :Sleep-Talk]]
["OU", :Mega-Manectric, "Special Attacker", ["", "", :Timid, [0, 0, 4, 252, 0, 252]], [:Thunderbolt, :Volt-Switch, :Overheat, :Hidden-Power-Ice]]
["OU", :Mega-Gardevoir, "Offensive", ["", "", :Timid, [0, 0, 24, 232, 0, 252]], [:Hyper-Voice, :Psyshock, :Focus-Blast, :Will-O-Wisp]]
["OU", :Mega-Gardevoir, "Calm Mind", ["", "", :Modest, [0, 0, 24, 232, 0, 252]], [:Calm-Mind, :Hyper-Voice, :Psyshock, :Focus-Blast]]
["OU", :Crawdaunt, "Wallbreaker", ["Life Orb", :Adaptability, :Adamant, [4, 252, 0, 0, 0, 252]], [:Knock-Off, :Crabhammer, :Aqua-Jet, :Crunch]]
["OU", :Noivern, "Life Orb", ["Life Orb", :Infiltrator, :Timid, [0, 0, 4, 252, 0, 252]], [:Draco-Meteor, :Focus-Blast, :Hurricane, :Roost]]
["OU", :Mega-Gyarados, "Mega Dragon Dance", ["", "", :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Waterfall, :Earthquake, :Ice-Fang]]
["OU", :Gothitelle, "Choice Specs", ["Choice Specs", :Shadow-Tag, :Modest, [0, 0, 0, 252, 4, 252]], [:Psyshock, :Thunderbolt, :Hidden-Power-Fire, :Trick]]
["OU", :Exploud, "Choice Specs", ["Choice Specs", :Scrappy, :Modest, [4, 0, 0, 252, 0, 252]], [:Boomburst, :Overheat, :Focus-Blast, :Flamethrower]]
["OU", :Seismitoad, "Rain Sweeper", ["Life Orb", :Swift-Swim, :Modest, [80, 0, 4, 252, 0, 172]], [:Hydro-Pump, :Earth-Power, :Focus-Blast, :Sludge-Wave]]
["OU", :Empoleon, "Specially Defensive", ["Leftovers", :Torrent, :Calm, [248, 0, 8, 0, 252, 0]], [:Scald, :Toxic, :Roar, :Stealth-Rock]]
["OU", :Empoleon, "Choice Specs", ["Choice Specs", :Torrent, :Modest, [248, 0, 0, 252, 0, 8]], [:Hydro-Pump, :Flash-Cannon, :Grass-Knot, :Hidden-Power-Fire]]
["OU", :Mega-Alakazam, "Mega Special Attacker", ["Alakazite", :Magic-Guard, :Modest, [32, 0, 0, 252, 0, 224]], [:Psychic, :Focus-Blast, :Shadow-Ball, :Hidden-Power-Fire]]
["OU", :Alakazam, "Revenge Killer", ["Focus Sash", :Magic-Guard, :Timid, [0, 0, 4, 252, 0, 252]], [:Psychic, :Focus-Blast, :Shadow-Ball, :Thunder-Wave]]
["OU", :Landorus-T, "Choice Scarf", ["Choice Scarf", :Intimidate, :Jolly, [0, 252, 24, 0, 0, 232]], [:Earthquake, :U-turn, :Superpower, :Stone-Edge]]
["OU", :Landorus-T, "Double Dance", ["Leftovers", :Intimidate, :Adamant, [56, 220, 0, 0, 0, 232]], [:Swords-Dance, :Rock-Polish, :Earthquake, :Stone-Edge]]
["OU", :Landorus-T, "Defensive", ["Leftovers", :Intimidate, :Impish, [252, 0, 240, 0, 8, 8]], [:Stealth-Rock, :Earthquake, :U-turn, :Stone-Edge]]
["OU", :Reuniclus, "Trick Room", ["Life Orb", :Magic-Guard, :Quiet, [192, 0, 64, 252, 0, 0]], [:Trick-Room, :Psychic, :Focus-Blast, :Shadow-Ball]]
["OU", :Breloom, "Offensive", ["Focus Sash", :Technician, :Jolly, [0, 252, 4, 0, 0, 252]], [:Spore, :Bullet-Seed, :Mach-Punch, :Rock-Tomb]]
["OU", :Breloom, "Leech Seed", ["Toxic Orb", :Poison-Heal, :Careful, [252, 4, 0, 0, 252, 0]], [:Leech-Seed, :Drain-Punch, :Protect, :Spore]]
["OU", :Mega-Pinsir, "Swords Dance", ["", "", :Jolly, [0, 252, 0, 0, 4, 252]], [:Swords-Dance, :Return, :Close-Combat, :Quick-Attack]]
["OU", :Tentacruel, "Physically Defensive", ["Black Sludge", :Liquid-Ooze, :Bold, [224, 0, 252, 0, 0, 32]], [:Scald, :Rapid-Spin, :Acid-Spray, :Sludge-Bomb]]
["OU", :Mega-Absol, "All-Out Attacker", ["", "", :Jolly, [0, 252, 0, 32, 0, 224]], [:Sucker-Punch, :Knock-Off, :Fire-Blast, :Superpower]]
["OU", :Mega-Charizard-X, "Bulky Will-O-Wisp", ["", "", :Careful, [248, 0, 0, 0, 148, 112]], [:Earthquake, :Dragon-Claw, :Will-O-Wisp, :Roost]]
["OU", :Mega-Charizard-X, "Bulky Dragon Dance", ["", "", :Adamant, [144, 252, 0, 0, 0, 112]], [:Dragon-Dance, :Dragon-Claw, :Earthquake, :Roost]]
["OU", :Mega-Charizard-X, "Dragon Dance", ["", "", :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Flare-Blitz, :Dragon-Claw, :Earthquake]]
["OU", :Mega-Charizard-Y, "Drought Wallbreaker", ["", "", :Timid, [0, 0, 4, 252, 0, 252]], [:Fire-Blast, :Solar-Beam, :Focus-Blast, :Roost]]
["OU", :Goodra, "Assault Vest", ["Assault Vest", :Sap-Sipper, :Modest, [240, 0, 0, 252, 0, 16]], [:Draco-Meteor, :Fire-Blast, :Sludge-Bomb, :Earthquake]]
["OU", :Gourgeist-Small, "SubSeed", ["Leftovers", :Frisk, :Timid, [252, 0, 32, 0, 0, 224]], [:Will-O-Wisp, :Leech-Seed, :Substitute, :Protect]]
["OU", :Clefable, "Magic Guard + Calm Mind", ["Leftovers", :Magic-Guard, :Calm, [252, 0, 160, 0, 96, 0]], [:Calm-Mind, :Moonblast, :Soft-Boiled, :Flamethrower]]
["OU", :Clefable, "Stealth Rock", ["Leftovers", :Magic-Guard, :Calm, [252, 0, 160, 0, 96, 0]], [:Stealth-Rock, :Moonblast, :Fire-Blast, :Soft-Boiled]]
["OU", :Clefable, "Physically Defensive", ["Leftovers", :Unaware, :Bold, [252, 0, 252, 0, 4, 0]], [:Moonblast, :Wish, :Protect, :Heal-Bell]]
["OU", :Latios, "Choice Scarf", ["Choice Scarf", :Levitate, :Timid, [0, 0, 0, 252, 4, 252]], [:Draco-Meteor, :Psyshock, :Hidden-Power-Fire, :Trick]]
["OU", :Latios, "Life Orb", ["Life Orb", :Levitate, :Timid, [0, 0, 0, 252, 4, 252]], [:Draco-Meteor, :Psyshock, :Hidden-Power-Fire, :Roost]]
["OU", :Latios, "Dual Screen Support", ["Light Clay", :Levitate, :Timid, [252, 0, 0, 0, 4, 252]], [:Reflect, :Light-Screen, :Memento, :Draco-Meteor]]
["OU", :Starmie, "Reflect Type", ["Leftovers", :Natural-Cure, :Timid, [248, 0, 0, 0, 16, 244]], [:Reflect-Type, :Scald, :Rapid-Spin, :Recover]]
["OU", :Starmie, "Offensive Spinner", ["Life Orb", :Analytic, :Timid, [4, 0, 0, 252, 0, 252]], [:Hydro-Pump, :Ice-Beam, :Psyshock, :Rapid-Spin]]
["OU", :Tangrowth, "Knock it Off, Mojonbo Rules Here!", ["Leftovers", :Regenerator, :Relaxed, [252, 0, 252, 0, 4, 0]], [:Giga-Drain, :Knock-Off, :Sleep-Powder, :Hidden-Power-Ice]]
["OU", :Tangrowth, "Assault Vest", ["Assault Vest", :Regenerator, :Sassy, [252, 0, 4, 0, 252, 0]], [:Leaf-Storm, :Knock-Off, :Earthquake, :Hidden-Power-Ice]]
["OU", :Azumarill, "Choice Band", ["Choice Band", :Huge-Power, :Adamant, [88, 252, 4, 0, 0, 164]], [:Aqua-Jet, :Play-Rough, :Knock-Off, :Waterfall]]
["OU", :Azumarill, "Belly Drum", ["Sitrus Berry", :Huge-Power, :Adamant, [92, 252, 0, 0, 0, 164]], [:Belly-Drum, :Aqua-Jet, :Play-Rough, :Waterfall]]
["OU", :Azumarill, "Assault Vest", ["Assault Vest", :Huge-Power, :Adamant, [240, 252, 0, 0, 16, 0]], [:Aqua-Jet, :Play-Rough, :Knock-Off, :Waterfall]]
["OU", :Jirachi, "Paraflinch", ["Leftovers", :Serene-Grace, :Adamant, [252, 252, 0, 0, 4, 0]], [:Iron-Head, :Body-Sla, :U-turn, :Zen-Headbut]]
["OU", :Jirachi, "Choice Scarf", ["Choice Scarf", :Serene-Grace, :Jolly, [0, 252, 0, 0, 4, 252]], [:Iron-Head, :Zen-Headbut, :U-turn, :Tric]]
["OU", :Jirachi, "Wishmaker", ["Leftovers", :Serene-Grace, :Careful, [252, 0, 4, 0, 252, 0]], [:Wish, :Iron-Head, :Thunder-Wav, :Protec]]
["OU", :Mega-Aggron, "RestTalk", ["", "", :Impish, [252, 0, 16, 0, 240, 0]], [:Rest, :Sleep-Talk, :Iron-Head, :Earthquake]]
["OU", :Mega-Aggron, "Tank", ["", "", :Impish, [252, 0, 16, 0, 240, 0]], [:Stealth-Rock, :Iron-Head, :Ice-Punch, :Earthquake]]
["OU", :Kyurem-B, "Substitute Attacker", ["Leftovers", "", :Mild, [56, 0, 0, 252, 0, 200]], [:Substitute, :Ice-Beam, :Fusion-Bolt, :Earth-Power]]
["OU", :Kyurem-B, "Specially Based Mixed Attacker", ["Life Orb", "", :Mild, [0, 56, 0, 252, 0, 200]], [:Ice-Beam, :Fusion-Bolt, :Earth-Power, :Roost]]
["OU", :Kyurem-B, "Choice Scarf", ["Choice Scarf", "", :Naughty, [0, 252, 0, 32, 0, 224]], [:Outrage, :Dragon-Claw, :Fusion-Bolt, :Ice-Beam]]
["OU", :Kyurem-B, "Physically Based Mixed Attacker", ["Life Orb", "", :Lonely, [0, 252, 0, 56, 0, 200]], [:Dragon-Claw, :Fusion-Bolt, :Ice-Beam, :Iron-Head]]
["OU", :Latias, "Bulky Defog", ["Life Orb", :Levitate, :Timid, [72, 0, 0, 184, 0, 252]], [:Defog, :Draco-Meteor, :Psyshock, :Roost]]
["OU", :Cobalion, "Offensive Pivot", ["Leftovers", :Justified, :Jolly, [140, 112, 0, 0, 0, 252]], [:Close-Combat, :Volt-Switch, :Iron-Head, :Taunt]]
["OU", :Diancie, "Tank", ["Leftovers", :Clear-Body, :Quiet, [252, 4, 0, 252, 0, 0]], [:Stealth-Rock, :Diamond-Storm, :Moonblast, :Hidden-Power-Fire]]
["OU", :Mega-Aerodactyl, "Stallbreaker", ["", "", :Adamant, [0, 244, 44, 0, 0, 220]], [:Taunt, :Aerial-Ace, :Aqua-Tail, :Roost]]
["OU", :Mega-Aerodactyl, "Offensive", ["", "", :Adamant, [0, 212, 44, 0, 0, 252]], [:Stone-Edge, :Earthquake, :Ice-Fang, :Aerial-Ace]]
["OU", :Bisharp, "Defiant Attacker", ["BlackGlasses", :Defiant, :Adamant, [4, 252, 0, 0, 0, 252]], [:Knock-Off, :Sucker-Punch, :Iron-Head, :Pursuit]]
["OU", :Kyurem, "SubRoost", ["Leftovers", :Pressure, :Modest, [56, 0, 0, 200, 0, 252]], [:Substitute, :Roost, :Ice-Beam, :Earth-Power]]
["OU", :Togekiss, "Stallbreaker", ["Leftovers", :Serene-Grace, :Modest, [0, 0, 4, 252, 0, 252]], [:Nasty-Plot, :Air-Slash, :Roost, :Heal-Bell]]
["OU", :Togekiss, "Defensive", ["Leftovers", :Serene-Grace, :Calm, [248, 0, 0, 8, 252, 0]], [:Roost, :Air-Slash, :Thunder-Wave, :Defog]]
["OU", :Togekiss, "Baton Pass", ["Leftovers", :Serene-Grace, :Calm, [252, 0, 0, 0, 240, 16]], [:Baton-Pass, :Nasty-Plot, :Roost, :Air-Slash]]
["OU", :Mega-Venusaur, "Offensive", ["Venusaurite", :Chlorophyll, :Modest, [232, 0, 0, 252, 4, 20]], [:Giga-Drain, :Sludge-Bomb, :Hidden-Power-Fire, :Synthesis]]
["OU", :Mega-Venusaur, "Defensive", ["Venusaurite", :Chlorophyll, :Bold, [252, 0, 240, 0, 0, 16]], [:Giga-Drain, :Sludge-Bomb, :Synthesis, :Leech-Seed]]
["OU", :Manaphy, "Calm Mind", ["Leftovers", :Hydration, :Bold, [252, 0, 240, 0, 0, 16]], [:Calm-Mind, :Rest, :Rain-Dance, :Scald]]
["OU", :Manaphy, "Tail Glow + Rain Dance", ["Leftovers", :Hydration, :Timid, [96, 0, 0, 252, 0, 160]], [:Tail-Glow, :Rain-Dance, :Scald, :Psychic]]
["OU", :Manaphy, "Tail Glow", ["Leftovers", :Hydration, :Timid, [80, 0, 0, 252, 0, 176]], [:Tail-Glow, :Surf, :Ice-Beam, :Energy-Ball]]
["OU", :Klefki, "Dual Screens", ["Light Clay", :Prankster, :Impish, [252, 0, 252, 0, 4, 0]], [:Reflect, :Light-Screen, :Spikes, :Fairy-Lock]]
["OU", :Mega-Garchomp, "Mixed", ["", "", :Naughty, [0, 4, 0, 252, 0, 252]], [:Earthquake, :Draco-Meteor, :Fire-Blast, :Stone-Edge]]
["OU", :Kabutops, "Physical Attacker", ["Life Orb", :Swift-Swim, :Adamant, [0, 252, 4, 0, 0, 252]], [:Waterfall, :Stone-Edge, :Swords-Dance, :Aqua-Jet]]
["OU", :Mega-Venusaur, "Offensive", ["", "", :Modest, [232, 0, 0, 252, 4, 20]], [:Giga-Drain, :Sludge-Bomb, :Hidden-Power-Fire, :Synthesis]]
["OU", :Mega-Venusaur, "Defensive", ["", "", :Bold, [252, 0, 240, 0, 0, 16]], [:Giga-Drain, :Sludge-Bomb, :Synthesis, :Leech-Seed]]
["OU", :Sylveon, "Calm Mind + Baton Pass", ["Leftovers", :Pixilate, :Bold, [252, 0, 244, 0, 0, 12]], [:Calm-Mind, :Baton-Pass, :Substitute, :Hyper-Voice]]
["OU", :Sylveon, "Cleric", ["Leftovers", :Pixilate, :Bold, [252, 0, 220, 0, 36, 0]], [:Hyper-Voice, :Wish, :Protect, :Heal-Bell]]
["OU", :Sylveon, "Choice Specs", ["Choice Specs", :Pixilate, :Modest, [244, 0, 0, 252, 0, 12]], [:Hyper-Voice, :Psyshock, :Shadow-Ball, :Hidden-Power-Fire]]
["OU", :Mega-Gardevoir, "Offensive", ["Gardevoirite", :Trace, :Timid, [0, 0, 24, 232, 0, 252]], [:Hyper-Voice, :Psyshock, :Focus-Blast, :Will-O-Wisp]]
["OU", :Mega-Gardevoir, "Calm Mind", ["Gardevoirite", :Trace, :Modest, [0, 0, 24, 232, 0, 252]], [:Calm-Mind, :Hyper-Voice, :Psyshock, :Focus-Blast]]
["OU", :Mega-Scizor, "Offensive Swords Dance", ["", "", :Adamant, [0, 252, 0, 0, 4, 252]], [:Swords-Dance, :Bullet-Punch, :Knock-Off, :Superpower]]
["OU", :Mega-Scizor, "Baton Pass", ["", "", :Impish, [248, 0, 236, 0, 0, 24]], [:Swords-Dance, :Baton-Pass, :Roost, :Bullet-Punch]]
["OU", :Mega-Scizor, "Roost + 3 Attacks", ["", "", :Adamant, [248, 96, 0, 0, 164, 0]], [:Roost, :U-turn, :Bullet-Punch, :Knock-Off]]
["OU", :Mega-Scizor, "Bulky Swords Dance", ["", "", :Impish, [248, 84, 0, 0, 176, 0]], [:Swords-Dance, :Roost, :Bullet-Punch, :Knock-Off]]
["OU", :Mega-Scizor, "Defog", ["", "", :Impish, [252, 4, 252, 0, 0, 0]], [:Defog, :Roost, :Bullet-Punch, :U-turn]]
["OU", :Quagsire, "Physically Defensive", ["Leftovers", :Unaware, :Relaxed, [252, 0, 252, 0, 4, 0]], [:Scald, :Earthquake, :Recover, :Toxic]]
["OU", :Mega-Gyarados, "Mega Dragon Dance", ["Gyaradosite", :Intimidate, :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Waterfall, :Earthquake, :Ice-Fang]]
["OU", :Gyarados, "Offensive Dragon Dance", ["Lum Berry", :Moxie, :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Waterfall, :Bounce, :Stone-Edge]]
["OU", :Gyarados, "Bulky Dragon Dance", ["Leftovers", :Intimidate, :Adamant, [88, 192, 4, 0, 0, 224]], [:Substitute, :Dragon-Dance, :Waterfall, :Bounce]]
["OU", :Gyarados, "RestTalk", ["Leftovers", :Intimidate, :Careful, [248, 0, 0, 0, 252, 8]], [:Waterfall, :Rest, :Sleep-Talk, :Thunder-Wave]]
["OU", :Heatran, "Choice Scarf", ["Choice Scarf", :Flash-Fire, :Modest, [0, 0, 0, 252, 4, 252]], [:Overheat, :Flash-Cannon, :Earth-Power, :Stone-Edge]]
["OU", :Heatran, "Offensive Air Balloon", ["Air Balloon", :Flash-Fire, :Timid, [12, 0, 0, 252, 0, 244]], [:Stealth-Rock, :Fire-Blast, :Taunt, :Will-O-Wisp]]
["OU", :Heatran, "Specially Defensive", ["Leftovers", :Flash-Fire, :Calm, [248, 0, 0, 0, 192, 68]], [:Lava-Plume, :Toxic, :Taunt, :Protect]]
["OU", :Slowking, "Assault Vest", ["Assault Vest", :Regenerator, :Modest, [248, 0, 0, 164, 96, 0]], [:Scald, :Fire-Blast, :Future-Sight, :Power-Gem]]
["OU", :Slowking, "Specially Defensive", ["Leftovers", :Regenerator, :Calm, [252, 0, 44, 0, 212, 0]], [:Scald, :Psyshock, :Thunder-Wave, :Slack-Off]]
["OU", :Hawlucha, "Swords Dance", ["Power Herb", :Unburden, :Adamant, [8, 252, 0, 0, 0, 248]], [:Swords-Dance, :Acrobatics, :High-Jump-Kick, :Sky-Attack]]
["OU", :Smeargle, "Sticky Web", ["Focus Sash", :Own-Tempo, :Timid, [96, 0, 120, 0, 40, 252]], [:Sticky-Web, :Stealth-Rock, :Spore, :Magic-Coat]]
["OU", :Whimsicott, "Support", ["Lagging Tail", :Prankster, :Impish, [252, 0, 252, 0, 4, 0]], [:Encore, :U-turn, :Memento, :Switcheroo]]
["OU", :Mega-Houndoom, "Nasty Plot", ["", "", :Timid, [0, 0, 4, 252, 0, 252]], [:Nasty-Plot, :Fire-Blast, :Dark-Pulse, :Taunt]]
["OU", :Mega-Medicham, "All-Out Attacker", ["Medichamite", :Pure-Power, :Adamant, [16, 240, 0, 0, 0, 252]], [:High-Jump-Kick, :Zen-Headbutt, :Fake-Out, :Ice-Punch]]
["OU", :Mega-Medicham, "Wallbreaker", ["Medichamite", :Pure-Power, :Adamant, [16, 240, 0, 0, 0, 252]], [:High-Jump-Kick, :Zen-Headbutt, :Ice-Punch, :Substitute]]
["OU", :Gengar, "Hex", ["Black Sludge", :Levitate, :Timid, [8, 0, 0, 248, 0, 252]], [:Hex, :Taunt, :Will-O-Wisp, :Sludge-Wave]]
["OU", :Gengar, "SubSplit", ["Life Orb", :Levitate, :Timid, [0, 0, 4, 252, 0, 252]], [:Substitute, :Pain-Split, :Shadow-Ball, :Focus-Blast]]
["OU", :Gengar, "Life Orb Attacker", ["Life Orb", :Levitate, :Timid, [0, 0, 0, 252, 4, 252]], [:Shadow-Ball, :Sludge-Wave, :Focus-Blast, :Taunt]]
["OU", :Rotom-W, "Defensive", ["Leftovers", :Levitate, :Bold, [248, 0, 216, 0, 0, 44]], [:Volt-Switch, :Hydro-Pump, :Will-O-Wisp, :Pain-Split]]
["OU", :Rotom-W, "Specially Defensive", ["Leftovers", :Levitate, :Calm, [252, 0, 0, 0, 212, 44]], [:Volt-Switch, :Hydro-Pump, :Will-O-Wisp, :Pain-Split]]
["OU", :Rotom-H, "Choice Scarf", ["Choice Scarf", :Levitate, :Timid, [4, 0, 0, 252, 0, 252]], [:Overheat, :Volt-Switch, :Hidden-Power-Ice, :Trick]]
["OU", :Rotom-H, "Defensive", ["Leftovers", :Levitate, :Bold, [252, 0, 252, 0, 4, 0]], [:Overheat, :Volt-Switch, :Will-O-Wisp, :Pain-Split]]
["OU", :Weavile, "Life Orb", ["Life Orb", :Pressure, :Jolly, [0, 252, 24, 0, 0, 232]], [:Knock-Off, :Ice-Shard, :Ice-Punch, :Low-Kick]]
["OU", :Keldeo, "Choice Specs", ["Choice Specs", "", :Timid, [0, 0, 0, 252, 4, 252]], [:Hydro-Pump, :Secret-Sword, :Scald, :Icy-Wind]]
["OU", :Keldeo, "Choice Scarf", ["Choice Scarf", "", :Timid, [0, 0, 4, 252, 0, 252]], [:Hydro-Pump, :Scald, :Secret-Sword, :Hidden-Power-Electric]]
["OU", :Keldeo, "SubCM", ["Leftovers", "", :Timid, [0, 0, 0, 252, 4, 252]], [:Calm-Mind, :Substitute, :Scald, :Secret-Sword]]
["OU", :Keldeo, "Endeavor", ["Salac Berry", :Justified, :Timid, [8, 0, 0, 248, 0, 252]], [:Endeavor, :Substitute, :Hydro-Pump, :Secret-Sword]]
["OU", :Keldeo, "Calm Mind", ["Leftovers", :Justified, :Timid, [0, 0, 0, 252, 4, 252]], [:Calm-Mind, :Hydro-Pump, :Secret-Sword, :Hidden-Power-Flying]]
["OU", :Mega-Manectric, "Special Attacker", ["Manectite", :Lightningrod, :Timid, [0, 0, 4, 252, 0, 252]], [:Thunderbolt, :Volt-Switch, :Overheat, :Hidden-Power-Ice]]
["OU", :Entei, "All-Out Attacker", ["Choice Band", "", :Adamant, [0, 252, 4, 0, 0, 252]], [:Sacred-Fire, :Extreme-Speed, :Stone-Edge, :Bulldoze]]
["OU", :Mega-Swampert, "Swift Swim", ["", "", :Adamant, [104, 252, 0, 0, 0, 152]], [:Waterfall, :Earthquake, :Ice-Punch, :Low-Kick]]
["OU", :Mega-Blastoise, "Rapid Spin", ["", "", :Modest, [236, 0, 0, 252, 0, 20]], [:Rapid-Spin, :Scald, :Dark-Pulse, :Aura-Sphere]]
["OU", :Mandibuzz, "Utility", ["Leftovers", :Overcoat, :Bold, [248, 0, 136, 0, 108, 16]], [:Foul-Play, :Roost, :Taunt, :Defog]]
["OU", :Volcarona, "Bulky Quiver Dance", ["Leftovers", :Flame-Body, :Bold, [248, 0, 136, 0, 0, 124]], [:Quiver-Dance, :Fire-Blast, :Giga-Drain, :Roost]]
["OU", :Volcarona, "Offensive Quiver Dance", ["Passho Berry", :Flame-Body, :Modest, [96, 0, 0, 252, 0, 160]], [:Quiver-Dance, :Fire-Blast, :Giga-Drain, :Hidden-Power-Ground]]
["OU", :Gorebyss, "SmashPass", ["White Herb", :Swift-Swim, :Calm, [252, 0, 0, 0, 4, 252]], [:Shell-Smash, :Baton-Pass, :Surf, :Substitute]]
["OU", :Bronzong, "Special Tank", ["Leftovers", :Levitate, :Sassy, [252, 4, 0, 0, 252, 0]], [:Gyro-Ball, :Earthquake, :Stealth-Rock, :Hidden-Power-Ice]]
["OU", :Bronzong, "Trick Room Support", ["Mental Herb", :Levitate, :Sassy, [252, 4, 0, 0, 252, 0]], [:Trick-Room, :Stealth-Rock, :Gyro-Ball, :Explosion]]
["OU", :Ferrothorn, "Utility", ["Leftovers", :Iron-Barbs, :Relaxed, [252, 0, 88, 0, 168, 0]], [:Stealth-Rock, :Leech-Seed, :Gyro-Ball, :Protect]]
["OU", :Mega-Aerodactyl, "Stallbreaker", ["Aerodactylite", :Pressure, :Adamant, [0, 244, 44, 0, 0, 220]], [:Taunt, :Aerial-Ace, :Aqua-Tail, :Roost]]
["OU", :Mega-Aerodactyl, "Offensive", ["Aerodactylite", :Pressure, :Adamant, [0, 212, 44, 0, 0, 252]], [:Stone-Edge, :Earthquake, :Ice-Fang, :Aerial-Ace]]
["OU", :Doublade, "Mixed Wall", ["Eviolite", :No-Guard, :Sassy, [252, 4, 0, 0, 252, 0]], [:Gyro-Ball, :Toxic, :Sleep-Talk, :Rest]]
["OU", :Politoed, "Offensive", ["Damp Rock", :Drizzle, :Modest, [172, 0, 0, 252, 0, 84]], [:Hydro-Pump, :Ice-Beam, :Focus-Blast, :Hypnosis]]
["OU", :Politoed, "Specially Defensive", ["Damp Rock", :Drizzle, :Calm, [252, 0, 0, 4, 252, 0]], [:Scald, :Toxic, :Encore, :Hypnosis]]
["OU", :Cofagrigus, "Trick Room Sweeper", ["Leftovers", "", :Quiet, [248, 0, 8, 252, 0, 0]], [:Trick-Room, :Nasty-Plot, :Shadow-Ball, :Will-O-Wisp]]
["OU", :Magnezone, "Choice Scarf", ["Choice Scarf", :Magnet-Pull, :Timid, [0, 0, 4, 252, 0, 252]], [:Volt-Switch, :Hidden-Power-Fire, :Flash-Cannon, :Thunderbolt]]
["OU", :Magnezone, "Choice Specs", ["Choice Specs", :Magnet-Pull, :Modest, [172, 0, 0, 252, 0, 84]], [:Volt-Switch, :Hidden-Power-Fire, :Flash-Cannon, :Thunderbolt]]
["OU", :Magnezone, "Magnet Rise", ["Air Balloon", :Magnet-Pull, :Modest, [128, 0, 0, 252, 0, 128]], [:Magnet-Rise, :Hidden-Power-Fire, :Flash-Cannon, :Thunderbolt]]
["OU", :Rhyperior, "Defensive", ["Leftovers", :Solid-Rock, :Adamant, [212, 44, 252, 0, 0, 0]], [:Stealth-Rock, :Earthquake, :Stone-Edge, :Ice-Punch]]
["OU", :Mega-Pinsir, "Swords Dance", ["Pinsirite", :Hyper-Cutter, :Jolly, [0, 252, 0, 0, 4, 252]], [:Swords-Dance, :Return, :Close-Combat, :Quick-Attack]]
["OU", :Raikou, "Choice Specs", ["Choice Specs", "", :Timid, [32, 0, 0, 252, 0, 224]], [:Thunderbolt, :Volt-Switch, :Hidden-Power-Ice, :Shadow-Ball]]
["OU", :Raikou, "Assault Vest", ["Assault Vest", "", :Timid, [0, 0, 0, 252, 32, 224]], [:Thunderbolt, :Volt-Switch, :Hidden-Power-Ice, :Shadow-Ball]]
["OU", :Raikou, "Calm Mind", ["Leftovers", "", :Timid, [32, 0, 0, 252, 0, 224]], [:Calm-Mind, :Thunderbolt, :Hidden-Power-Ice, :Extrasensory]]
["OU", ":Porygon2", "Trick Room Support", ["Eviolite", :Trace, :Quiet, [252, 0, 0, 252, 4, 0]], [:Trick-Room, :Ice-Beam, :Thunderbolt, :Recover]]
["OU", ":Porygon2", "Specially Defensive", ["Eviolite", :Trace, :Calm, [252, 0, 4, 0, 252, 0]], [:Thunderbolt, :Ice-Beam, :Shadow-Ball, :Recover]]
["OU", ":Porygon2", "Physically Defensive", ["Eviolite", :Trace, :Bold, [252, 0, 252, 0, 4, 0]], [:Thunderbolt, :Ice-Beam, :Recover, :Toxic]]
["OU", :Mamoswine, "Physical Attacker", ["Life Orb", :Thick-Fat, :Naive, [0, 240, 0, 16, 0, 252]], [:Earthquake, :Ice-Shard, :Icicle-Spear, :Freeze-Dry]]
["OU", :Mamoswine, "Focus Sash", ["Focus Sash", :Thick-Fat, :Jolly, [0, 252, 4, 0, 0, 252]], [:Stealth-Rock, :Icicle-Spear, :Ice-Shard, :Earthquake]]
["OU", :Mega-Alakazam, "Mega Special Attacker", ["", "", :Modest, [32, 0, 0, 252, 0, 224]], [:Psychic, :Focus-Blast, :Shadow-Ball, :Hidden-Power-Fire]]
["OU", :Chansey, "Wish Support", ["Eviolite", :Natural-Cure, :Bold, [4, 0, 252, 0, 252, 0]], [:Wish, :Soft-Boiled, :Seismic-Toss, :Toxic]]
["OU", :Chansey, "Support", ["Eviolite", :Natural-Cure, :Bold, [4, 0, 252, 0, 252, 0]], [:Soft-Boiled, :Heal-Bell, :Toxic, :Seismic-Toss]]
["OU", :Infernape, "MixApe", ["Life Orb", :Iron-Fist, :Naive, [0, 212, 0, 44, 0, 252]], [:Flare-Blitz, :Close-Combat, :Hidden-Power-Ice, :Thunder-Punch]]
["OU", :Greninja, "All-Out Attacker", ["Life Orb", :Protean, :Timid, [0, 0, 4, 252, 0, 252]], [:Hydro-Pump, :Ice-Beam, :Extrasensory, :Grass-Knot]]
["OU", :Greninja, "Spikes", ["Life Orb", :Protean, :Timid, [0, 0, 4, 252, 0, 252]], [:Spikes, :Hydro-Pump, :Ice-Beam, :Extrasensory]]
["OU", :Tornadus-T, "Life Orb", ["Life Orb", :Regenerator, :Naive, [0, 76, 0, 216, 0, 216]], [:Hurricane, :Superpower, :U-turn, :Taunt]]
["OU", :Tornadus-T, "Assault Vest", ["Assault Vest", "", :Timid, [132, 0, 0, 160, 0, 216]], [:Hurricane, :Focus-Blast, :Knock-Off, :U-turn]]
["OU", :Amoonguss, "Defensive", ["Black Sludge", :Regenerator, :Bold, [252, 0, 136, 0, 120, 0]], [:Spore, :Giga-Drain, :Hidden-Power-Fire, :Clear-Smog]]
["OU", :Chesnaught, "Physical Tank", ["Leftovers", :Bulletproof, :Impish, [252, 0, 252, 0, 4, 0]], [:Spiky-Shield, :Leech-Seed, :Hammer-Arm, :Spikes]]
["OU", :Mega-Heracross, "Offensive", ["Heracronite", :Moxie, :Jolly, [0, 252, 4, 0, 0, 252]], [:Close-Combat, :Pin-Missile, :Rock-Blast, :Swords-Dance]]
["OU", :Froslass, "Suicide Spiker", ["Focus Sash", :Cursed-Body, :Timid, [4, 0, 0, 252, 0, 252]], [:Taunt, :Spikes, :Destiny-Bond, :Ice-Beam]]
["OU", :Terrakion, "Choice Scarf", ["Choice Scarf", :Justified, :Jolly, [0, 252, 0, 0, 4, 252]], [:Close-Combat, :Stone-Edge, :Earthquake, :X-Scissor]]
["OU", :Terrakion, "Life Orb Attacker", ["Life Orb", :Justified, :Naive, [0, 252, 0, 4, 0, 252]], [:Close-Combat, :Stone-Edge, :Earthquake, :Hidden-Power-Ice]]
["OU", :Terrakion, "Stealth Rock", ["Focus Sash", :Justified, :Jolly, [0, 252, 0, 0, 4, 252]], [:Stealth-Rock, :Close-Combat, :Stone-Edge, :Taunt]]
["OU", :Conkeldurr, "Assault Vest", ["Assault Vest", :Guts, :Adamant, [0, 252, 0, 0, 236, 20]], [:Drain-Punch, :Mach-Punch, :Ice-Punch, :Poison-Jab]]
["OU", :Excadrill, "Sand Rush Sweeper", ["Life Orb", :Sand-Rush, :Adamant, [0, 252, 4, 0, 0, 252]], [:Earthquake, :Iron-Head, :Rock-Slide, :Rapid-Spin]]
["OU", :Excadrill, "Choice Scarf", ["Choice Scarf", :Mold-Breaker, :Jolly, [0, 252, 4, 0, 0, 252]], [:Earthquake, :Iron-Head, :Rock-Slide, :Rapid-Spin]]
["OU", :Thundurus, "Prankster Attacker", ["Life Orb", :Prankster, :Timid, [0, 0, 4, 252, 0, 252]], [:Thunder-Wave, :Thunderbolt, :Hidden-Power-Ice, :Focus-Blast]]
["OU", :Thundurus, "Mixed Attacker", ["Life Orb", :Defiant, :Naive, [0, 76, 0, 180, 0, 252]], [:Thunderbolt, :Knock-Off, :Superpower, :Hidden-Power-Ice]]
["OU", :Thundurus, "Nasty Plot", ["Leftovers", :Prankster, :Timid, [0, 0, 4, 252, 0, 252]], [:Nasty-Plot, :Thunderbolt, :Hidden-Power-Flying, :Thunder-Wave]]
["OU", :Sableye, "Prankster Utility", ["Leftovers", :Prankster, :Impish, [252, 0, 252, 0, 4, 0]], [:Will-O-Wisp, :Recover, :Taunt, :Knock-Off]]
["OU", :Dugtrio, "Trapper", ["Focus Sash", :Arena-Trap, :Naive, [0, 252, 4, 0, 0, 252]], [:Earthquake, :Reversal, :Memento, :Stealth-Rock]]
["OU", :Scizor, "Choice Band", ["Choice Band", :Technician, :Adamant, [248, 252, 0, 0, 8, 0]], [:U-turn, :Bullet-Punch, :Knock-Off, :Superpower]]
["OU", :Mega-Scizor, "Baton Pass", ["Scizorite", :Light-Metal, :Impish, [248, 0, 236, 0, 0, 24]], [:Swords-Dance, :Baton-Pass, :Roost, :Bullet-Punch]]
["OU", :Mega-Scizor, "Roost + 3 Attacks", ["Scizorite", :Light-Metal, :Adamant, [248, 96, 0, 0, 164, 0]], [:Roost, :U-turn, :Bullet-Punch, :Knock-Off]]
["OU", :Mega-Scizor, "Bulky Swords Dance", ["Scizorite", :Light-Metal, :Impish, [248, 84, 0, 0, 176, 0]], [:Swords-Dance, :Roost, :Bullet-Punch, :Knock-Off]]
["OU", :Mega-Scizor, "Defog", ["Scizorite", :Light-Metal, :Impish, [252, 4, 252, 0, 0, 0]], [:Defog, :Roost, :Bullet-Punch, :U-turn]]
["OU", :Mega-Scizor, "Offensive Swords Dance", ["Scizorite", :Light-Metal, :Adamant, [0, 252, 0, 0, 4, 252]], [:Swords-Dance, :Bullet-Punch, :Knock-Off, :Superpower]]
["OU", :Zapdos, "Defensive", ["Leftovers", :Pressure, :Bold, [252, 0, 168, 68, 0, 20]], [:Thunderbolt, :Roost, :Defog, :Heat-Wave]]
["OU", :Tyranitar, "Choice Scarf", ["Choice Scarf", :Sand-Stream, :Jolly, [0, 252, 4, 0, 0, 252]], [:Pursuit, :Crunch, :Earthquake, :Stone-Edge]]
["OU", :Mega-Tyranitar, "Dragon Dance", ["Tyranitarite", :Sand-Stream, :Jolly, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Stone-Edge, :Ice-Punch, :Earthquake]]
["OU", :Tyranitar, "Support", ["Leftovers", :Sand-Stream, :Relaxed, [248, 0, 252, 0, 8, 0]], [:Stealth-Rock, :Crunch, :Ice-Beam, :Earthquake]]
["OU", :Moltres, "SubToxic", ["Leftovers", :Pressure, :Calm, [248, 0, 0, 0, 160, 100]], [:Substitute, :Toxic, :Roost, :Flamethrower]]
["OU", :Mega-Tyranitar, "Dragon Dance", ["", "", :Jolly, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Stone-Edge, :Ice-Punch, :Earthquake]]
["OU", :Charizard, "Bulky Will-O-Wisp", ["Charizardite X", :Blaze, :Careful, [248, 0, 0, 0, 148, 112]], [:Earthquake, :Dragon-Claw, :Will-O-Wisp, :Roost]]
["OU", :Charizard, "Bulky Dragon Dance", ["Charizardite X", :Blaze, :Adamant, [144, 252, 0, 0, 0, 112]], [:Dragon-Dance, :Dragon-Claw, :Earthquake, :Roost]]
["OU", :Charizard, "Drought Wallbreaker", ["Charizardite Y", :Blaze, :Timid, [0, 0, 4, 252, 0, 252]], [:Fire-Blast, :Solar-Beam, :Focus-Blast, :Roost]]
["OU", :Charizard, "Dragon Dance", ["Charizardite X", :Blaze, :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Flare-Blitz, :Dragon-Claw, :Earthquake]]
["OU", :Mega-Houndoom, "Nasty Plot", ["Houndoominite", :Flash-Fire, :Timid, [0, 0, 4, 252, 0, 252]], [:Nasty-Plot, :Fire-Blast, :Dark-Pulse, :Taunt]]
["OU", :Landorus, "Rock Polish", ["Life Orb", :Sheer-Force, :Rash, [0, 8, 0, 252, 0, 248]], [:Rock-Polish, :Earth-Power, :Psychic, :Knock-Off]]
["OU", :Landorus, "Calm Mind", ["Life Orb", :Sheer-Force, :Timid, [0, 0, 4, 252, 0, 252]], [:Calm-Mind, :Earth-Power, :Psychic, :Focus-Blast]]
["OU", :Landorus, "Special Attacker", ["Life Orb", :Sheer-Force, :Naive, [0, 0, 4, 252, 0, 252]], [:Earth-Power, :Psychic, :Focus-Blast, :Knock-Off]]
["OU", :Mega-Medicham, "All-Out Attacker", ["", "", :Adamant, [16, 240, 0, 0, 0, 252]], [:High-Jump-Kick, :Zen-Headbutt, :Fake-Out, :Ice-Punch]]
["OU", :Mega-Medicham, "Wallbreaker", ["", "", :Adamant, [16, 240, 0, 0, 0, 252]], [:High-Jump-Kick, :Zen-Headbutt, :Ice-Punch, :Substitute]]
["OU", :Azelf, "Suicide Lead", ["Focus Sash", :Levitate, :Naive, [0, 196, 0, 60, 0, 252]], [:Stealth-Rock, :Taunt, :Explosion, :Fire-Blast]]
["OU", :Azelf, "Dual Screens", ["Light Clay", :Levitate, :Timid, [240, 0, 44, 0, 0, 224]], [:Reflect, :Light-Screen, :Taunt, :Stealth-Rock]]
["OU", :Azelf, "Rain Dance", ["Damp Rock", :Levitate, :Jolly, [240, 0, 44, 0, 0, 252]], [:Rain-Dance, :Stealth-Rock, :Taunt, :Explosion]]
["OU", :Skarmory, "Spikes", ["Leftovers", :Sturdy, :Bold, [252, 0, 172, 0, 0, 84]], [:Spikes, :Whirlwind, :Roost, :Taunt]]
["OU", :Skarmory, "Physically Defensive", ["Leftovers", :Sturdy, :Bold, [252, 0, 252, 0, 4, 0]], [:Roost, :Whirlwind, :Stealth-Rock, :Defog]]
["OU", :Diggersby, "Swords Dance", ["Focus Sash", :Huge-Power, :Adamant, [4, 252, 0, 0, 0, 252]], [:Swords-Dance, :Earthquake, :Return, :Quick-Attack]]
["OU", :Diggersby, "Choice Scarf", ["Choice Scarf", :Huge-Power, :Adamant, [4, 252, 0, 0, 0, 252]], [:Return, :Earthquake, :Wild-Charge, :U-turn]]
["OU", :Garchomp, "Swords Dance", ["Lum Berry", :Rough-Skin, :Jolly, [4, 252, 0, 0, 0, 252]], [:Swords-Dance, :Earthquake, :Outrage, :Stone-Edge]]
["OU", :Garchomp, "Choice Scarf", ["Choice Scarf", :Rough-Skin, :Naive, [0, 252, 0, 4, 0, 252]], [:Outrage, :Earthquake, :Rock-Slide, :Fire-Blast]]
["OU", :Mega-Garchomp, "Mixed", ["Garchompite", :Rough-Skin, :Naughty, [0, 4, 0, 252, 0, 252]], [:Earthquake, :Draco-Meteor, :Fire-Blast, :Stone-Edge]]
["OU", :Garchomp, "Offensive Stealth Rock", ["Focus Sash", :Rough-Skin, :Naive, [0, 252, 0, 4, 0, 252]], [:Stealth-Rock, :Earthquake, :Outrage, :Fire-Blast]]
["OU", :Garchomp, "Tank", ["Rocky Helmet", :Rough-Skin, :Impish, [252, 0, 252, 0, 4, 0]], [:Earthquake, :Dragon-Tail, :Stealth-Rock, :Toxic]]
["OU", :Dragonite, "Choice Band", ["Choice Band", :Multiscale, :Adamant, [0, 252, 4, 0, 0, 252]], [:Outrage, :Extreme-Speed, :Thunder-Punch, :Superpower]]
["OU", :Dragonite, "Bulky Roost", ["Leftovers", :Multiscale, :Adamant, [216, 64, 0, 0, 228, 0]], [:Roost, :Dragon-Claw, :Extreme-Speed, :Fire-Punch]]
["OU", :Dragonite, "Dragon Dance", ["Lum Berry", :Multiscale, :Adamant, [0, 252, 4, 0, 0, 252]], [:Dragon-Dance, :Outrage, :Extreme-Speed, :Fire-Punch]]
["OU", :Lucario, "Life Orb Attacker", ["Life Orb", :Justified, :Adamant, [0, 252, 4, 0, 0, 252]], [:Close-Combat, :Swords-Dance, :Extreme-Speed, :Iron-Tail]]
["OU", :Scolipede, "QuickPass", ["Mental Herb", :Speed-Boost, :Timid, [248, 0, 20, 0, 0, 240]], [:Protect, :Substitute, :Baton-Pass, :Swords-Dance]]
["OU", :Scolipede, "Offensive", ["Life Orb", :Speed-Boost, :Adamant, [16, 252, 4, 0, 0, 236]], [:Megahorn, :Earthquake, :Poison-Jab, :Protect]]
["OU", :Ludicolo, "Rain Sweeper", ["Life Orb", :Swift-Swim, :Modest, [0, 0, 0, 252, 4, 252]], [:Hydro-Pump, :Giga-Drain, :Ice-Beam, :Focus-Blast]]
["OU", :Salamence, "Choice Scarf", ["Choice Scarf", :Moxie, :Naughty, [0, 252, 0, 4, 0, 252]], [:Outrage, :Dragon-Claw, :Earthquake, :Fire-Blast]]
["OU", :Mew, "Stallbreaker", ["Leftovers", :Synchronize, :Impish, [252, 0, 104, 0, 0, 152]], [:Taunt, :Soft-Boiled, :Will-O-Wisp, :Knock-Off]]
["OU", :Mew, "Entry Hazard Control", ["Leftovers", :Synchronize, :Impish, [252, 0, 104, 0, 0, 152]], [:Defog, :Soft-Boiled, :Will-O-Wisp, :Knock-Off]]
["OU", :Hippowdon, "Mixed Wall", ["Leftovers", :Sand-Stream, :Impish, [252, 0, 144, 0, 112, 0]], [:Earthquake, :Stealth-Rock, :Slack-Off, :Stone-Edge]]
["OU", :Thundurus-T, "Nasty Plot", ["Leftovers", :Volt-Absorb, :Timid, [4, 0, 0, 252, 0, 252]], [:Nasty-Plot, :Thunderbolt, :Hidden-Power-Flying, :Focus-Blast]]
["OU", :Blissey, "Wish Passer", ["Leftovers", :Natural-Cure, :Bold, [4, 0, 252, 0, 252, 0]], [:Wish, :Soft-Boiled, :Seismic-Toss, :Toxic]]
["OU", :Blissey, "Cleric", ["Leftovers", :Natural-Cure, :Bold, [4, 0, 252, 0, 252, 0]], [:Soft-Boiled, :Heal-Bell, :Toxic, :Seismic-Toss]]
["OU", :Talonflame, "Stallbreaker", ["Leftovers", :Gale-Wings, :Careful, [248, 0, 0, 0, 252, 8]], [:Brave-Bird, :Taunt, :Roost, :Will-O-Wisp]]
["OU", :Talonflame, "Swords Dance + Natural Gift", ["Liechi Berry", :Gale-Wings, :Jolly, [88, 252, 0, 0, 0, 168]], [:Swords-Dance, :Natural-Gift, :Brave-Bird, :Flare-Blitz]]
["OU", :Talonflame, "Bulk Up", ["Leftovers", :Gale-Wings, :Careful, [248, 0, 0, 0, 252, 8]], [:Bulk-Up, :Brave-Bird, :Roost, :Will-O-Wisp]]
["OU", :Talonflame, "Swords Dance", ["Sharp Beak", :Gale-Wings, :Jolly, [120, 252, 0, 0, 0, 136]], [:Swords-Dance, :Brave-Bird, :Flare-Blitz, :Roost]]
["OU", :Talonflame, "Revenge Killer", ["Choice Band", :Gale-Wings, :Adamant, [0, 252, 4, 0, 0, 252]], [:Brave-Bird, :Flare-Blitz, :U-turn, :Tailwind]]
["OU", :Zygarde, "SubCoil", ["Leftovers", :Aura-Break, :Careful, [200, 0, 0, 0, 252, 56]], [:Substitute, :Coil, :Earthquake, :Dragon-Tail]]
["OU", :Zygarde, "Parashuffler", ["Leftovers", :Aura-Break, :Impish, [200, 0, 252, 0, 0, 56]], [:Glare, :Earthquake, :Dragon-Tail, :Substitute]]
["OU", :Zygarde, "DDRest", ["Chesto Berry", :Aura-Break, :Adamant, [120, 252, 0, 0, 0, 136]], [:Dragon-Dance, :Rest, :Earthquake, :Outrage]]
["OU", :Zygarde, "Dragon Dance", ["Life Orb", :Aura-Break, :Adamant, [4, 252, 0, 0, 0, 252]], [:Dragon-Dance, :Earthquake, :Outrage, :Stone-Edge]]
["OU", :Mega-Blastoise, "Rapid Spin", ["Blastoisinite", :Rain-Dish, :Modest, [236, 0, 0, 252, 0, 20]], [:Rapid-Spin, :Scald, :Dark-Pulse, :Aura-Sphere]]
["OU", :Chandelure, "Stallbreaker", ["Leftovers", :Flash-Fire, :Modest, [160, 0, 0, 156, 0, 192]], [:Shadow-Ball, :Fire-Blast, :Substitute, :Taunt]]
["OU", :Chandelure, "Choice Scarf", ["Choice Scarf", :Flash-Fire, :Modest, [0, 0, 4, 252, 0, 252]], [:Overheat, :Shadow-Ball, :Hidden-Power-Fighting, :Trick]]
["OU", :Staraptor, "Choice Band", ["Choice Band", :Reckless, :Jolly, [0, 252, 4, 0, 0, 252]], [:Brave-Bird, :Double-Edge, :Close-Combat, :U-turn]]
["OU", :Staraptor, "Choice Scarf", ["Choice Scarf", :Reckless, :Jolly, [0, 252, 4, 0, 0, 252]], [:Brave-Bird, :Double-Edge, :Close-Combat, :U-turn]]
["OU", :Mega-Heracross, "Offensive", ["", "", :Jolly, [0, 252, 4, 0, 0, 252]], [:Close-Combat, :Pin-Missile, :Rock-Blast, :Swords-Dance]]
["OU", :Suicune, "CroCune", ["Leftovers", "", :Bold, [252, 0, 252, 4, 0, 0]], [:Calm-Mind, :Scald, :Rest, :Sleep-Talk]]
["OU", :Gastrodon, "Physically Defensive", ["Leftovers", :Storm-Drain, :Bold, [252, 0, 252, 0, 4, 0]], [:Scald, :Earth-Power, :Toxic, :Recover]]
["OU", :Haxorus, "Stallbreaker", ["Lum Berry", :Mold-Breaker, :Adamant, [16, 252, 0, 0, 0, 240]], [:Swords-Dance, :Outrage, :Earthquake, :Poison-Jab]]
["OU", :Haxorus, "Dragon Dance", ["Life Orb", :Mold-Breaker, :Adamant, [16, 252, 0, 0, 0, 240]], [:Dragon-Dance, :Outrage, :Earthquake, :Taunt]]
["OU", :Espeon, "Dual Screens", ["Light Clay", :Magic-Bounce, :Timid, [252, 0, 4, 0, 0, 252]], [:Light-Screen, :Reflect, :Baton-Pass, :Yawn]]
["OU", :Mega-Swampert, "Swift Swim", ["Swampertite", :Damp, :Adamant, [104, 252, 0, 0, 0, 152]], [:Waterfall, :Earthquake, :Ice-Punch, :Low-Kick]]
["OU", :Kingdra, "CritDra", ["Scope Lens", :Sniper, :Modest, [64, 0, 0, 252, 0, 192]], [:Focus-Energy, :Draco-Meteor, :Hydro-Pump, :Agility]]
["OU", :Kingdra, "Mixed Rain Sweeper", ["Life Orb", "", :Rash, [0, 64, 0, 252, 0, 192]], [:Hydro-Pump, :Draco-Meteor, :Outrage, :Waterfall]]
["OU", :Kingdra, "Rain Wallbreaker", ["Choice Specs", "", :Modest, [64, 0, 0, 252, 0, 192]], [:Hydro-Pump, :Draco-Meteor, :Surf, :Ice-Beam]]
